"""
Mock product data for demo/fallback when live scrapers are blocked.
Prices are realistic INR values as of mid-2025.
"""

MOCK_PRODUCTS = {
    "amul milk": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Amul Taaza Toned Milk 500ml",     "price": 28,  "mrp": 30,  "unit": "500ml", "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 6.7},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Amul Taaza Toned Milk 500ml",     "price": 27,  "mrp": 30,  "unit": "500ml", "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 10.0},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Amul Taaza Toned Milk 500ml",     "price": 29,  "mrp": 30,  "unit": "500ml", "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 3.3},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Amul Taaza Toned Milk 500ml",     "price": 30,  "mrp": 30,  "unit": "500ml", "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Amul Taaza Toned Milk 500ml",     "price": 29,  "mrp": 30,  "unit": "500ml", "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 3.3},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Amul Taaza Toned Milk 500ml",     "price": 31,  "mrp": 32,  "unit": "500ml", "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": 3.1},
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Amul Gold Full Cream Milk 1L",    "price": 68,  "mrp": 72,  "unit": "1L",    "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 5.6},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Amul Gold Full Cream Milk 1L",    "price": 65,  "mrp": 72,  "unit": "1L",    "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 9.7},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Amul Gold Full Cream Milk 1L",    "price": 70,  "mrp": 72,  "unit": "1L",    "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 2.8},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Amul Gold Full Cream Milk 1L",    "price": 72,  "mrp": 72,  "unit": "1L",    "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": None},
    ],
    "amul butter": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Amul Butter Pasteurised 100g",    "price": 52,  "mrp": 56,  "unit": "100g",  "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 7.1},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Amul Butter Pasteurised 100g",    "price": 50,  "mrp": 56,  "unit": "100g",  "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 10.7},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Amul Butter Pasteurised 100g",    "price": 54,  "mrp": 56,  "unit": "100g",  "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 3.6},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Amul Butter Pasteurised 100g",    "price": 55,  "mrp": 56,  "unit": "100g",  "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 1.8},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Amul Butter 500g",                "price": 265, "mrp": 280, "unit": "500g",  "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 5.4},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Amul Butter Pasteurised 100g",    "price": 56,  "mrp": 56,  "unit": "100g",  "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": None},
    ],
    "tata salt": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Tata Salt Iodized 1kg",           "price": 20,  "mrp": 22,  "unit": "1kg",   "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 9.1},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Tata Salt Iodized 1kg",           "price": 19,  "mrp": 22,  "unit": "1kg",   "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 13.6},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Tata Salt Iodized 1kg",           "price": 21,  "mrp": 22,  "unit": "1kg",   "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 4.5},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Tata Salt Iodized 1kg",           "price": 22,  "mrp": 22,  "unit": "1kg",   "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Tata Salt Iodized 1kg",           "price": 20,  "mrp": 22,  "unit": "1kg",   "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 9.1},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Tata Salt Iodized 1kg",           "price": 21,  "mrp": 22,  "unit": "1kg",   "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": 4.5},
    ],
    "maggi noodles": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Maggi 2-Minute Noodles Masala 70g", "price": 14,  "mrp": 15,  "unit": "70g",   "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 6.7},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Maggi 2-Minute Noodles Masala 70g", "price": 13,  "mrp": 15,  "unit": "70g",   "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 13.3},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Maggi 2-Minute Noodles 4-Pack 280g","price": 55,  "mrp": 60,  "unit": "280g",  "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 8.3},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Maggi 2-Minute Noodles Masala 70g", "price": 15,  "mrp": 15,  "unit": "70g",   "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Maggi 2-Minute Noodles 12-Pack",   "price": 156, "mrp": 180, "unit": "12x70g","image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 13.3},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Maggi 2-Minute Noodles Masala 70g", "price": 14,  "mrp": 15,  "unit": "70g",   "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": 6.7},
    ],
    "aashirvaad atta": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Aashirvaad Whole Wheat Atta 5kg",  "price": 268, "mrp": 290, "unit": "5kg",   "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 7.6},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Aashirvaad Whole Wheat Atta 5kg",  "price": 262, "mrp": 290, "unit": "5kg",   "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 9.7},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Aashirvaad Whole Wheat Atta 5kg",  "price": 275, "mrp": 290, "unit": "5kg",   "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 5.2},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Aashirvaad Whole Wheat Atta 5kg",  "price": 280, "mrp": 290, "unit": "5kg",   "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 3.4},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Aashirvaad Whole Wheat Atta 5kg",  "price": 260, "mrp": 290, "unit": "5kg",   "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 10.3},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Aashirvaad Whole Wheat Atta 5kg",  "price": 270, "mrp": 290, "unit": "5kg",   "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": 6.9},
    ],
    "dairy milk": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Cadbury Dairy Milk Chocolate 38g", "price": 40,  "mrp": 45,  "unit": "38g",   "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 11.1},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Cadbury Dairy Milk Chocolate 38g", "price": 38,  "mrp": 45,  "unit": "38g",   "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 15.6},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Cadbury Dairy Milk Chocolate 38g", "price": 42,  "mrp": 45,  "unit": "38g",   "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 6.7},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Cadbury Dairy Milk 38g",          "price": 43,  "mrp": 45,  "unit": "38g",   "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": 4.4},
    ],
    "lays chips": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Lays Classic Salted 26g",          "price": 20,  "mrp": 20,  "unit": "26g",   "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Lays Classic Salted 26g",          "price": 18,  "mrp": 20,  "unit": "26g",   "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 10.0},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Lays Classic Salted 26g",          "price": 20,  "mrp": 20,  "unit": "26g",   "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Lays Magic Masala 52g",            "price": 35,  "mrp": 40,  "unit": "52g",   "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 12.5},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Lays Classic Salted 26g",          "price": 20,  "mrp": 20,  "unit": "26g",   "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": None},
    ],
    "parle-g biscuits": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Parle-G Original Glucose Biscuits 250g","price": 15, "mrp": 15,  "unit": "250g",  "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Parle-G Original Glucose Biscuits 250g","price": 14, "mrp": 15,  "unit": "250g",  "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 6.7},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Parle-G Original Glucose Biscuits 250g","price": 15, "mrp": 15,  "unit": "250g",  "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": None},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Parle-G Original Glucose Biscuits 250g","price": 15, "mrp": 15,  "unit": "250g",  "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": None},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Parle-G Gold Biscuits 500g",        "price": 28,  "mrp": 30,  "unit": "500g",  "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 6.7},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Parle-G Original Glucose Biscuits 250g","price": 15, "mrp": 15,  "unit": "250g",  "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": None},
    ],
    "fortune sunflower oil": [
        {"platform": "blinkit",   "platform_display": "Blinkit",          "platform_color": "#f8c200", "platform_logo": "B", "product_name": "Fortune Sunflower Oil 1L",         "price": 148, "mrp": 165, "unit": "1L",    "image_url": None, "product_url": "https://blinkit.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 10.3},
        {"platform": "zepto",     "platform_display": "Zepto",            "platform_color": "#8b5cf6", "platform_logo": "Z", "product_name": "Fortune Sunflower Oil 1L",         "price": 145, "mrp": 165, "unit": "1L",    "image_url": None, "product_url": "https://zeptonow.com", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 12.1},
        {"platform": "bigbasket", "platform_display": "BigBasket",        "platform_color": "#84cc16", "platform_logo": "BB","product_name": "Fortune Sunflower Oil 1L",         "price": 155, "mrp": 165, "unit": "1L",    "image_url": None, "product_url": "https://bigbasket.com", "in_stock": True, "delivery_time": "Next day", "discount_pct": 6.1},
        {"platform": "swiggy",    "platform_display": "Swiggy Instamart", "platform_color": "#fb923c", "platform_logo": "S", "product_name": "Fortune Sunflower Oil 1L",         "price": 152, "mrp": 165, "unit": "1L",    "image_url": None, "product_url": "https://swiggy.com/instamart", "in_stock": True, "delivery_time": "10 mins", "discount_pct": 7.9},
        {"platform": "flipkart",  "platform_display": "Flipkart",         "platform_color": "#2563eb", "platform_logo": "F", "product_name": "Fortune Sunflower Oil 5L",         "price": 690, "mrp": 750, "unit": "5L",    "image_url": None, "product_url": "https://flipkart.com", "in_stock": True, "delivery_time": "1-2 days", "discount_pct": 8.0},
        {"platform": "amazon",    "platform_display": "Amazon Fresh",     "platform_color": "#ff9900", "platform_logo": "A", "product_name": "Fortune Sunflower Oil 1L",         "price": 150, "mrp": 165, "unit": "1L",    "image_url": None, "product_url": "https://amazon.in/fresh", "in_stock": True, "delivery_time": "2-4 hrs", "discount_pct": 9.1},
    ],
}


def find_mock(query: str) -> list:
    """Return mock results for a query. Fuzzy-matches against known keys."""
    q = query.lower().strip()
    # Exact match
    if q in MOCK_PRODUCTS:
        return MOCK_PRODUCTS[q]
    # Partial match
    for key, products in MOCK_PRODUCTS.items():
        if key in q or q in key:
            return products
        # word overlap
        q_words = set(q.split())
        k_words = set(key.split())
        if len(q_words & k_words) >= 1 and len(q_words & k_words) / max(len(q_words), len(k_words)) > 0.4:
            return products
    return []
